const products = [
  {
    name: "Camiseta Angular",
    img: "/assets/t-shirt/angular.jpg",
    price: 20,
    type: "t-shirt",
    description: "Uma camiseta do framework Angular",
  },
  {
    name: "Camiseta Code",
    img: "/assets/t-shirt/code.jpg",
    price: 50,
    type: "t-shirt",
    description: "Camiseta Code clássica :D",
  },
  {
    name: "Camiseta Docker",
    img: "/assets/t-shirt/docker.jpg",
    price: 50,
    type: "t-shirt",
    description: "Camiseta massa do Docker",
  },
  {
    name: "Camiseta git blame",
    img: "/assets/t-shirt/git-blame.jpg",
    price: 65,
    type: "t-shirt",
    description: "Camiseta do git blame pra causar discórdia",
  },
  {
    name: "Meia outro framework de JS?",
    img: "/assets/socks/another-framework-socks.jpg",
    price: 15,
    type: "socks",
    description: "Seria essa meia mais um framework JavaScript?",
  },
  {
    name: "Moletom Angular",
    img: "/assets/warm-clothes/angular-hoodie.jpg",
    price: 120,
    type: "hoodie",
    description: "Fique quentinho com essa belezura :)",
  },
  {
    name: "Camiseta Git",
    img: "/assets/t-shirt/git.jpg",
    price: 50,
    type: "t-shirt",
    description: "Aquela camisa especial",
  },
  {
    name: "Camiseta Go",
    img: "/assets/t-shirt/go-lang.jpg",
    price: 50,
    type: "t-shirt",
    description: "Camiseta com seu mascote preferido",
  },
  {
    name: "Camiseta JS no coração",
    img: "/assets/t-shirt/js-in-heartbeat.jpg",
    price: 50,
    type: "t-shirt",
    description: "JavaScript fazendo o nosso coração bater",
  },
  {
    name: "Camiseta Mago do opensource",
    img: "/assets/t-shirt/open-sourcerer.jpg",
    price: 50,
    type: "t-shirt",
    description: "Open source é mágico 🧙♂️",
  },
  {
    name: "Camiseta Python",
    img: "/assets/t-shirt/python-lang.jpg",
    price: 50,
    type: "t-shirt",
    description: "Camiseta da linguagem de programação python",
  },
  {
    name: "Camiseta Works in my machine",
    img: "/assets/t-shirt/works-in-my-machine.jpg",
    price: 50,
    type: "t-shirt",
    description: "Quando só funciona na sua máquina",
  },
  {
    name: "Meia Game dev",
    img: "/assets/socks/gamer-dev-socks.jpg",
    price: 15,
    type: "socks",
    description: "Pra te aquecer com muito estilo ⚛️",
  },
  {
    name: "Meia Java",
    img: "/assets/socks/java-socks.jpg",
    price: 15,
    type: "socks",
    description: "Aquele javinha padrão :D",
  },
  {
    name: "Meia JS Love",
    img: "/assets/socks/js-love-socks.jpg",
    price: 15,
    type: "socks",
    description: "Amor ao nosso JavaScript ❤",
  },
  {
    name: "Meia React",
    img: "/assets/socks/react-socks.jpg",
    price: 15,
    type: "socks",
    description: "Meia para te aquecer e fazer belas UI's",
  },
  {
    name: "Meia Vue Codes",
    img: "/assets/socks/vue-socks.jpg",
    price: 15,
    type: "socks",
    description: "Uma meia pronta pra te fazer entender melhor Vue :)",
  },
  {
    name: "Moletom Git",
    img: "/assets/warm-clothes/git-hoodie.jpg",
    price: 120,
    type: "hoodie",
    description: "Moletom pra te manter quentinho e bem versionado",
  },
  {
    name: "Moletom JavaScript",
    img: "/assets/warm-clothes/js-hoodie.jpg",
    price: 120,
    type: "hoodie",
    description:
      "Moletom pra te manter quentinho e estiloso com aquela logo de JS <3",
  },
  {
    name: "Moletom Linux Mint",
    img: "/assets/warm-clothes/linux-mint-hoodie.jpg",
    price: 120,
    type: "hoodie",
    description: "Moletom com a melhor logo de todas as distribuições linux?",
  },
  {
    name: "Moletom Vue",
    img: "/assets/warm-clothes/vue-hoodie.jpg",
    price: 120,
    type: "hoodie",
    description: "Moletom que está pronto pra te aquecer",
  },
];

module.exports = products;
